# Generated by Django 5.0.6 on 2024-07-13 05:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Appin', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Name_for_page',
        ),
    ]
